name = "story_bakery/check_moonwave_syntax"
version = "0.1.0"
license = "MIT"
includes = [
    "pesde.toml",
    "scripts/init.luau",
]

[target]
environment = "lune"

[target.scripts]
check_moonwave_syntax = "scripts/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.1"
lune = "^0.10.4"
