name = "story_bakery/build_docs"
version = "0.1.0"
license = "MIT"
includes = [
    "pesde.toml",
    "src/**",
]

[target]
environment = "lune"

[target.scripts]
build_docs = "src/init.luau"

[dependencies]
validate_moonwave = { workspace = "story_bakery/validate_moonwave", version = "^", target = "lune" }

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.1"
lune = "^0.10.4"
