name = "story_bakery/watch_darklua"
version = "0.1.0"
license = "MIT"
includes = [
    "pesde.toml",
    "src/**",
]

[target]
environment = "lune"

[target.scripts]
watch_darklua = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.1"
lune = "^0.10.4"
